
name: Build Mods

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Package Character
        run: |
          cd Character/HueChaMinh ; zip -r ../HueChaMinh.zip . * ; cd ..
          mv HueChaMinh.zip HueChaMinh.deli
          rm -rf HueChaMinh/
          cd .. ; mv Character/ DootyEnjoyer6-Hue_Cha_Minh/
          ls

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: DootyEnjoyer6-Hue_Cha_Minh
          path: DootyEnjoyer6-Hue_Cha_Minh

      - name: Package Modpack
        run: |
          mv Modpack/ DootyEnjoyer6-Hue_Cha_Minh_Content_Pack
          ls

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: DootyEnjoyer6-Hue_Cha_Minh_Content_Pack
          path: DootyEnjoyer6-Hue_Cha_Minh_Content_Pack
