name: Build Character

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Package Character
        run: |
          cd Hue-Cha-Minh/
          mkdir DootyEnjoyer6-Hue_Cha_Minh
          cp manifest.json Hue-Cha-Minh/DootyEnjoyer6-Hue_Cha_Minh/
          cp CHANGELOG.md Hue-Cha-Minh/DootyEnjoyer6-Hue_Cha_Minh/
          cp README.md Hue-Cha-Minh/DootyEnjoyer6-Hue_Cha_Minh/
          cp icon.png Hue-Cha-Minh/DootyEnjoyer6-Hue_Cha_Minh/
          cd Hue-Cha-Minh/HueChaMinh
          zip -r HueChaMinh.zip HueChaMinh
          mv HueChaMinh.zip HueChaMinh.deli
          mv HueChaMinh.deli Hue-Cha-Minh/DootyEnjoyer6-Hue_Cha_Minh/
          ls

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: DootyEnjoyer6-Hue_Cha_Minh
          path: DootyEnjoyer6-Hue_Cha_Minh
          
