name: Build Character

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Package Character
        run: |
          mkdir DootyEnjoyer6-Hue_Cha_Minh
          cp manifest.json DootyEnjoyer6-Hue_Cha_Minh/
          cp CHANGELOG.md DootyEnjoyer6-Hue_Cha_Minh/
          cp README.md DootyEnjoyer6-Hue_Cha_Minh/
          cp icon.png DootyEnjoyer6-Hue_Cha_Minh/
          mv HueChaMinh DootyEnjoyer6-Hue_Cha_Minh/
          ls

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: DootyEnjoyer6-Hue_Cha_Minh
          path: DootyEnjoyer6-Hue_Cha_Minh
          
